// Auto-generated list of images from /public/images
export const galleryImages: { src: string; alt: string }[] = [
    { src: "/images/act1.jpg", alt: "" },
    { src: "/images/act2.jpg", alt: "" },
    { src: "/images/act5.jpg", alt: "" },
    { src: "/images/act6.jpg", alt: "" },
    { src: "/images/act7.jpg", alt: "" },
    { src: "/images/act8.jpg", alt: "" },
    { src: "/images/act9.jpg", alt: "" },
    { src: "/images/ADTS Banner...jpg", alt: "" },
    { src: "/images/ADTS Sticker.jpg", alt: "" },
    { src: "/images/alliance.jpg", alt: "" },
    { src: "/images/hilarie.jpg", alt: "" },
    { src: "/images/image1.jpg", alt: "" },
    { src: "/images/image1a.jpeg", alt: "" },
    { src: "/images/image2.jpg", alt: "" },
    { src: "/images/image2a.jpeg", alt: "" },
    { src: "/images/image3.jpg", alt: "" },
    { src: "/images/image4.jpg", alt: "" },
    { src: "/images/image5.jpg", alt: "" },
    { src: "/images/image6.jpg", alt: "" },
    { src: "/images/image_1.jpeg", alt: "" },
    { src: "/images/image_10.jpeg", alt: "" },
    { src: "/images/Image_11.jpeg", alt: "" },
    { src: "/images/image_12.jpeg", alt: "" },
    { src: "/images/image_13.jpeg", alt: "" },
    { src: "/images/image_14.jpeg", alt: "" },
    { src: "/images/image_15.jpeg", alt: "" },
    { src: "/images/image_16.jpeg", alt: "" },
    { src: "/images/image_17.jpeg", alt: "" },
    { src: "/images/image_18.jpeg", alt: "" },
    { src: "/images/image_19.jpeg", alt: "" },
    { src: "/images/image_2.jpeg", alt: "" },
    { src: "/images/image_20.jpeg", alt: "" },
    { src: "/images/image_21.jpeg", alt: "" },
    { src: "/images/image_22.jpeg", alt: "" },
    { src: "/images/image_23.jpeg", alt: "" },
    { src: "/images/image_24.jpeg", alt: "" },
    { src: "/images/image_25.jpeg", alt: "" },
    { src: "/images/image_26.jpeg", alt: "" },
    { src: "/images/image_27.jpeg", alt: "" },
    { src: "/images/image_28.jpeg", alt: "" },
    { src: "/images/image_29.jpeg", alt: "" },
    { src: "/images/image_3.jpeg", alt: "" },
    { src: "/images/image_30.jpeg", alt: "" },
    { src: "/images/image_31.jpeg", alt: "" },
    { src: "/images/image_32.jpeg", alt: "" },
    { src: "/images/image_33.jpeg", alt: "" },
    { src: "/images/image_34.jpeg", alt: "" },
    { src: "/images/image_35.jpeg", alt: "" },
    { src: "/images/image_36.jpeg", alt: "" },
    { src: "/images/image_37.jpeg", alt: "" },
    { src: "/images/image_38.jpeg", alt: "" },
    { src: "/images/image_39.jpeg", alt: "" },
    { src: "/images/image_4.jpeg", alt: "" },
    { src: "/images/image_5.jpeg", alt: "" },
    { src: "/images/image_6.jpeg", alt: "" },
    { src: "/images/image_7.jpeg", alt: "" },
    { src: "/images/image_8.jpeg", alt: "" },
    { src: "/images/Image_9.jpeg", alt: "" },
];

export default galleryImages;
